---
title: "Download subsample of pollution data"
output: 
  html_notebook: 
    theme: simplex
    highlight: pygments
  html_document:
    theme: simplex
    highlight: pygments
author: "Vincent Bagilet, Léo Zabrocki"
date: "July 30, 2020"
---

```{r setup, include=FALSE, results='hide', warning=FALSE}
library(knitr)
opts_chunk$set(fig.path = "images/",
               cache.path = "cache/",
               cache = FALSE,
               echo = TRUE,
               message = FALSE,
               warning = FALSE)  
```  

```{r include=FALSE}
library(tidyverse)
library(europollution)
```

In this document, we download a subsample of the pollution data. To do so, we use the `europollution` package.

# Definition subsample

We choose to consider a subsample of 10%  of  air  pollution  stations (610 stations), randomly selected. The analysis focuses on a 5 years period, 2013-2018.

```{r}
set.seed(12)

# metadata <- ep_metadata() 
# save(metadata, file = "../Outputs/metadata.Rda")

load("../Outputs/metadata.Rda")

stations_id <- metadata$AirQualityStation %>% unique() 
subsample_stations_ids <- sample(stations_id, floor(length(stations_id)/10))

# save(subsample_stations_ids, file = "../Outputs/subsample_stations_ids.Rda")
```

# Download, rangle and clean data


```{r}
raw_subsample_pollution <- ep_download(stations_id = subsample_stations_ids, pollutants = c("O3", "PM10", "PM2.5", "NOx", "NO2", "SO2"), begin = 2013, end = 2018)

save(raw_subsample_pollution, file = "../Outputs/raw_subsample_pollution.Rda")

subsample_pollution <- raw_subsample_pollution %>% 
  ep_wrangle() %>% 
  ep_clean()

raw_subsample_pollution <- ep_download(stations = subsample_stations_ids, pollutants = c("O3", "PM10", "PM2.5", "NOX as NO2", "NO2", "SO2"), begin = 2013, end = 2018)
# raw_subsample_PM10 <- ep_download(stations = subsample_stations_ids, pollutants = "PM10", begin = 2013, end = 2018)
# save(raw_subsample_PM10, file = "../Outputs/raw_subsample_PM10.Rda")

save(raw_subsample_pollution, file = "../Outputs/raw_subsample_pollution.Rda")

wrangled_subsample_PM10 <- raw_subsample_PM10 %>% 
  ep_wrangle() 

subsample_PM10 <- wrangled_subsample_PM10 %>% 
  filter(!is.na(datetime_begin)) %>% #there is an issue in the data for 1 observation
  ep_complete_dates()

save(subsample_PM10, file = "../Outputs/subsample_PM10.Rda")

```









