---
title: "Download public holidays data"
output: 
  html_notebook: 
    toc: yes
    theme: simplex
    highlight: pygments
  html_document:
    theme: simplex
    highlight: pygments
author: "Vincent Bagilet"
date: "May 19, 2020"
---

```{r setup, include=FALSE, results='hide', warning=FALSE}
library(knitr)
opts_chunk$set(fig.path = "images/",
               cache.path = "cache/",
               cache = FALSE,
               echo = TRUE,
               message = FALSE,
               warning = FALSE)  
```  

```{r include=FALSE}
library(tidyverse)
library(httr)
library(lubridate)
```

# Data description

The data comes from the following sources: 
- https://www.data.gouv.fr/fr/datasets/vacances-scolaires-par-zones/
- https://www.data.gouv.fr/fr/datasets/jours-feries-en-france/ 

# Download the data

## School holidays

```{r}
temp <- tempfile()
download.file("https://raw.githubusercontent.com/AntoineAugusti/vacances-scolaires/master/data.csv", temp)
school_holidays <- read_csv(temp) %>% 
  select(date, vacances_zone_a, vacances_zone_b, vacances_zone_c)
```

## Public holidays

```{r}
temp <- tempfile()
download.file("https://www.data.gouv.fr/fr/datasets/r/6637991e-c4d8-4cd6-854e-ce33c5ab49d5", temp)
public_holidays <- read_csv(temp) %>% 
  select(date) %>% #zone == "metropole" for all observations
  mutate(public_holiday = TRUE)
```

## Merge and save

```{r}
holidays <- school_holidays %>% 
  full_join(public_holidays) %>% 
  filter(year(date) >= 2013, year(date) < 2020) %>% 
  pivot_longer(starts_with("vacances"), names_to = "holiday_zone", names_prefix = "vacances_zone_", values_to = "school_holiday")

save(holidays, file = "../Outputs/holidays.Rda")
```





