---
title: "Graphs in the paper"
description: |
  In this document we build the version of the graphs that are in the paper.
author:
  - name: Vincent Bagilet 
    url: https://www.sipa.columbia.edu/experience-sipa/sipa-profiles/vincent-bagilet
    affiliation: Columbia University
    affiliation_url: https://www.columbia.edu/
  - name: Léo Zabrocki 
    url: https://www.parisschoolofeconomics.eu/en/
    affiliation: Paris School of Economics
    affiliation_url: https://www.parisschoolofeconomics.eu/en/
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
editor_options: 
  chunk_output_type: console
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
# code chunk option
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  # layout = "l-body-outset",
  dpi = 300
)
```

# Loading Packages and Data

We load the required packages and the data:

```{r set_up, message=FALSE, warning=FALSE}
library(here) # for files paths organization
library(tidyverse) # for data manipulation and visualization
library(knitr) # for compiling the document
# library(kableExtra) # for building nice table
# library(geomtextpath)

library(mediocrethemes)
set_mediocre_all(pal = "leo")

summary_evol_large <-readRDS(here("R/Outputs/summary_evol_large.RDS")) %>%
  mutate(sample_size = "large")

summary_evol_small <-readRDS(here("R/Outputs/summary_evol_small.RDS")) %>%
  mutate(sample_size = "small")

summary_evol_usual <-readRDS(here("R/Outputs/summary_evol_usual.RDS")) %>%
  mutate(sample_size = "usual")

summary_evol_all <- summary_evol_large %>% 
  bind_rows(summary_evol_small, summary_evol_usual) %>%
  mutate(
    id_method = case_when(id_method == "IV" ~ "Instrumental Variable",
                          id_method == "OLS" ~ "Standard Regression",
                          id_method == "reduced_form" ~ "Reduced-Form",
                          id_method == "RDD" ~ "Discontinuity Design"),
    n_obs = n_days*n_cities
  ) %>%
  pivot_longer(
    cols = c("power", "type_m", "mean_f_stat"),
    names_to = "metrics",
    values_to = "stat_value"
  ) %>% 
  mutate(
    metrics_name = case_when(metrics == "power" ~ "Statistical Power (%)",
                             metrics == "type_m" ~ "Exaggeration Ratio",
                             metrics == "mean_f_stat" ~ "F-Statistic",),
    id_method_name = fct_relevel(
      id_method,
      "Standard Regression",
      "Reduced-Form",
      "Instrumental Variable"
    )
  )
```

# Sample Size and Type M Error

```{r graph_n_cities, fig.width=10, fig.height=5}
summary_evol_all  %>%
  filter(id_method != "Discontinuity Design") %>%
  filter(outcome == "death_total") %>%
  filter(percent_effect_size == 1.0) %>%
  filter(p_obs_treat %in% c(NA, 0.5)) %>%
  filter(iv_strength %in% c(NA, 0.5)) %>%
  filter(metrics != "mean_f_stat") %>% 
  mutate(n_cities = as.factor(n_cities)) %>%
  ggplot(aes(x = n_days, y = stat_value, colour = n_cities)) +
  geom_line(size = 0.5, linetype = "dashed") +
  geom_point() +
  facet_grid(metrics_name ~ id_method_name, scale = "free", switch = "y") +
  labs(
    x = "Number of Days",
    y = NULL,
    color = "Number of Cities"
  ) +
  ylim(c(0, NA)) 


# save the graph
graph_type_m_sample_size %>%
  ggsave(
    .,
    filename = here::here(
      "3.outputs",
      "graph_type_m_sample_size_1.pdf"
    ),
    width = 30,
    height = 12,
    units = "cm"
  )
```

# Propotion of Exogenous Shocks 

```{r prop_shocks, fig.width=10, fig.height=5}
summary_evol_all %>%
  filter(id_method != "Standard Regression") %>%
  filter(n_obs %in% c(10000, 100000)) %>%
  filter(outcome == "death_total") %>%
  filter(percent_effect_size == 1.0) %>%
  filter(iv_strength %in% c(NA, 0.5)) %>%
  filter(metrics != "mean_f_stat") %>% 
  mutate(n_obs = ifelse(n_obs==10000, "10,000", "100,000")) %>%
  ggplot(aes(x = p_obs_treat, y = stat_value, colour = n_obs)) +
  geom_line(size = 0.5, linetype = "dashed") +
  geom_point(size = 1.5) +
  facet_grid(
    metrics_name ~ id_method_name, 
    scales = "free",
    switch = "y"
  ) +
  labs(
    x = "Proportion of Exogenous Shocks",
    y = NULL,
    color = "Number of Observations",
    title = "This is a test",
    subtitle = "blablablabla blabla"
  ) +
  ylim(c(0, NA)) +
  theme(
    legend.justification='left', 
    legend.margin = ggplot2::margin(l = -2.2, t = -0.5, unit = "cm")
  )


graph %>%
  ggsave(
    .,
    filename = here::here(
      "3.outputs",
      "graph_power_prop_exogenous_shocks.pdf"
    ),
    width = 30,
    height = 12,
    units = "cm",
    device = cairo_pdf
  )
```

# 

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.width=10, fig.height=5}
summary_evol_all %>%
  filter(id_method %in% c("Instrumental Variable")) %>%
  filter(n_days %in% c(1000, 2500)) %>%
  filter(outcome == "death_total") %>%
  filter(percent_effect_size == 1.0) %>%
  filter(p_obs_treat == 0.5) %>%
  mutate(n_cities = as.factor(n_cities)) %>%
  slice(-6) %>% #why??
  filter(n_obs %in% c(10000, 100000)) %>%
  mutate(n_obs = ifelse(n_obs == 10000, "10,000", "100,000")) %>%
  ggplot(aes(x = iv_strength, y = stat_value, colour = n_obs)) +
  geom_line(size = 0.5, linetype = "dashed") +
  geom_point(size = 1.5) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 6)) +
  facet_wrap(~ metrics_name, scale = "free_y") +
  labs(
    x = "Strength of the IV",
    y = NULL,
    color = "Number of Observations"
  ) 

graph %>%
  ggsave(
    .,
    filename = here::here("3.outputs",
                          "graph_power_issues_iv.pdf"),
    width = 30,
    height = 12,
    units = "cm",
    device = cairo_pdf
  )
```







