---
title: "Analysis of missing data patterns"
author:
  - name: Vincent Bagilet 
    url: https://www.sipa.columbia.edu/experience-sipa/sipa-profiles/vincent-bagilet
    affiliation: Columbia University
    affiliation_url: https://www.columbia.edu/
  - name: Léo Zabrocki 
    url: https://www.parisschoolofeconomics.eu/en/
    affiliation: Paris School of Economics
    affiliation_url: https://www.parisschoolofeconomics.eu/en/
date: "`r Sys.Date()`"
# output:
#   html_notebook:
#     toc: no
#     theme: simplex
#     highlight: pygments
#   html_document:
#     theme: simplex
#     highlight: pygments
# ---
output: distill::distill_article
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE, results='hide', warning=FALSE}
library(knitr)
opts_chunk$set(fig.path = "images/",
               cache.path = "cache/",
               cache = FALSE,
               echo = FALSE, #set to false to hide code
               message = FALSE,
               warning = FALSE,
               out.width = "85%",
               dpi = 300,
               fig.align = "center")  
```  

```{r include=FALSE}
library(tidyverse)
library(mediocrethemes)
library(lubridate)
# library(leaflet)

# set_mediocre_all()
```

Teexte 

```{r include=FALSE}
metadata_pollution <- readRDS("../Outputs/clean_metadata_pollution.RDS")
```

Autre texte

```{r fig.asp = 1}
metadata_pollution %>% 
  ggplot() + 
  # geom_point(aes(x = longitude, y = latitude)) + 
  geom_histogram(aes(x = elevation)) + 
  coord_flip() +
  labs(title = "Un super test de malade") +
  theme_minimal()
```





